site_name: brainslug documentation
pages:
- [index.md, Home, "Home"]
- [basics.md, "Basics"]
- [control-flow.md, "Control Flow"]
- [task.md, "Tasks"]
- [jpa-support.md, "JPA Support"]
- [spring-support.md, "Spring Support"]
- [bpmn.md, "BPMN Support"]
- [motivation.md, "Motivation and Design Goals"]
theme: readthedocs
markdown_extensions: [smarty, codehilite]
