site_name: brainslug documentation
pages:
- [index.md, Home, "Home"]
- [helloworld.md, "Hello World!"]
- [guide.md, "Developers Guide"]
- [bpmn.md, BPMN Support]
- [motivation.md, Motivation and Design Goals]
theme: readthedocs
markdown_extensions: [smarty, codehilite]
