## Tasks

### Registry

The brainslug context has a `Registry` where singletons of service classes can be registered:

[source, java]
context.getRegistry().registerService(Delegate.class, new Delegate());

or retrieved:

[source, java]
Delegate delegateService = context.getRegistry().getService(Delegate.class);

### Ways to define a task

#### Inline Task

[source, java]
----
include::{exampleBase}/brainslug/TaskExamples.java[tags=inline-task, indent=0]
----

In **Java 8** the task can be defined using a lambda expression:

[source, java]
----
ctx -> {
  ctx.service(MyService.class).doSomething();
}
----

#### Delegate class

If you do not want to specify the method by name, you can use the `Execute`-annotation to define which
method you want be executed for a task:

[source, java]
----
include::{projectBase}/execution/src/test/java/brainslug/flow/execution/token/TaskNodeExecutorTest.java[tags=test-delegate, indent=0]
----

[source, java]
----
include::{projectBase}/execution/src/test/java/brainslug/flow/execution/token/TaskNodeExecutorTest.java[tags=delegate-flow, indent=0]
----

#### Service Call

You may use service call definition, to directly define the invocation of a method during flow node definition.

[source, java]
----
include::{projectBase}/execution/src/test/java/brainslug/flow/execution/token/TaskNodeExecutorTest.java[tags=service-call, indent=0]
----

#### Typesafe Service Call

It possible to define service calls using a proxy-based approach similar to Mockito.

[source, java]
----
include::{projectBase}/execution/src/test/java/brainslug/AbstractExecutionTest.java[tags=test-service, indent=0]
----

[source, java]
----
include::{projectBase}/execution/src/test/java/brainslug/flow/execution/token/TaskNodeExecutorTest.java[tags=type-safe-call, indent=0]
----

In this case, the call to the service will be made at execution using the recorded argument values.
This will be done using reflection on the instance of the service, which must be available in the `Registry`.

#### Async Tasks
